### ISSUE TITLE
No closed chats history

### ISSUE THREAD

**Issue by LeeWiu** [LiveHelperChat/desktop#12]
Hi, after updating to v3.43, I can't see history on Closed Chat Tab.
![qt5](https://user-images.githubusercontent.com/1405188/94540088-bb6b2d00-024e-11eb-9dba-15ab9c03f0dd.png)

**Comment by remdex** [comment]
Hi,
Yes correct. It was intentionally removed because then there is a lot of chats it just hits performance to much. Same was done with unread chats.

Perhaps in the future I'll restore it, but only as optional.

**Comment by LeeWiu** [comment]
Ok, thanks, please restore only as optional, it's very usefull.
