### ISSUE TITLE
1.94v fonts or dpi to small

### ISSUE THREAD

**Issue by LeeWiu** [LiveHelperChat/desktop#13]
Hi, I updated from 193v and reading font is very small, was decreased from abous 12 to 9, can we have back old size or add an option to choose? 
Thanks

**Comment by remdex** [comment]
Can you paste screenshot about ehat font you are talking?

**Comment by LeeWiu** [comment]
Sure, in the picture looks bigger than reality
<img width="338" alt="lhc" src="https://user-images.githubusercontent.com/1405188/110931575-18f1c280-8333-11eb-83f2-ccbdf9a9b699.png">

**Comment by remdex** [comment]
This is not related to lhc as nothing changed regarding font. It's more related to your windows settings and monitor resolution :)

**Comment by LeeWiu** [comment]
I tested on 2 different pc with different resolutions, same small fonts, can you please provide link to download 1.93v?
