### ISSUE TITLE
Configuration scripts?

### ISSUE THREAD

**Issue by RCheesley** [LiveHelperChat/desktop#5]
Hi,

I notice that the desktop client has to be compiled from source, but I don't see any configuration files - might be missing something, but some guidance would be helpful.

Ruth

**Comment by remdex** [comment]
QT requires just one configuration file. Project file and it's
https://github.com/LiveHelperChat/desktop/blob/master/lhc.pro

Nothing more is required from QT part.
https://livehelperchat.com/article/view/67

**Comment by RCheesley** [comment]
OK, must be my lack of understanding.  I installed QT per the instructions, I have not used it before, so it's a bit of a leap of understanding knowing what to do next with the absence of any guidance/documentation.

**Comment by remdex** [comment]
After you install QT itself, there is Programer from qt itself, called Qt Creator, so you just open pro file and click compile etc. That's all.

**Comment by RCheesley** [comment]
Awesome, thank you for your patience.  A one-liner stating that in the readme would have saved me a lot of time :)
